[
  import ./ags
  import ./alacritty
  import ./aria2
  import ./awesome
  import ./bat
  import ./btop
  import ./cava
  import ./chromium
  import ./defaults
  import ./desktop
  import ./direnv
  import ./fastfetch
  import ./firefox
  import ./fzf
  import ./gaming
  import ./ghostty
  import ./git
  import ./hyprland
  import ./mpv
  import ./neovim
  import ./nixcord
  import ./nushell
  import ./picom
  import ./spotify-player
  import ./ssh
  import ./starship
  import ./tmux
  import ./waybar
  import ./wezterm
  import ./zathura
  import ./zoxide
]
